### ISSUE TITLE
Comments on base structure

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/tripal_ws_brapi#1]
## Changes
- Add `tripal_ws` as a dependency to the module.
- Make sure that other developers can override a single BrAPI call in their own module without having to duplicate all the code. This is needed to handle the case where they store their data differently but only for a single call. 
- Users should be able to access `[base]/v1/[...]/calls` as well as `[base]/v2/[...]/serverinfo` without needing to change configuration. This is needed to support the maximum number of BrAPPs
- This module should only handle BrAPI and should use the Tripal web services where possible.

## Comments
- `hook_menu` and `tripal_ws_vocabulary_handle_request` look good 👍 I like their simplicity.
- Overall class structure looks good 👍 
- Functional Test 👍 

## Next Steps
- This is a good point to start a "Developers Handbook" explaining the class structure of the module and the flow of methods.
- Automated testing for the current classes.

**Comment by reynoldtan** [comment]
Changes made to item 1 and 2. 
To implement a hook_alter (override):
1. create a function using the function below:
```
function MODULE_NAME_tripal_ws_brapi_CALL_alter(&$response) {
  // Prepare a query using information (call and parameters) in the $response['call_asset'] variable.
  // or alter item or items in the $response['payload'] and $response['metadata'] variables.
  // In the event of any error, use $response['error'] = 'message'.

  return $response
}

```
for example, an alter function for call commoncropnames in my_module would be
```function my_module_tripal_ws_brapi_commoncropnames_alter(&$response) { ... }```

Response parameter contains call assets - call name, parameters, payload and metadata
information. The call name and parameter can be used to construct a different query statement
while the payload and metadata can be used to alter particular item/s from response already prepared by the module.

2. Execute call

Item 3: access levels. Module supports [base]/v1/call and [base]/v2/core/serverinfo. The configuration only applies to levels before the brapi level, to conform to BrAPI specification

> To distinguish between multiple databases available from the same server, include a base path as part of the <server> identifier. An arbitrary number of levels can be inserted between the domain name and the brapi level, if needed.

> Example: https://test-server.brapi.org/maize_db_01/brapi/v1/markerprofiles/2939

> Example:` https://test-server.brapi.org/cornell/cals/wheat_db/brapi/v1/markerprofiles/2939

In our case, we can set it to mysite.com/web-services/lentils/brapi/v1/.... or just mysite.com/brapi/v1 (by setting to empty value)....

**Comment by laceysanderson** [comment]
This has been addressed. Still no automated testing though.
