### ISSUE TITLE
`totalPages` are off by one

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/tripal_ws_brapi#19]
There is an off-by-one error in the totalPages response field. Specifically, when there are 4 items and the `pageSize=4`, you expect to see `totalPages:1` but instead it's showing `0`. Same when you have `pageSize=1`, you expect to see `totalPages:4` but instead you see `3`. Despite this paging seems to work.

This bug was identified in PR #6 for the `programs` call. Since there are many outstanding PRs at this point, I haven't tested against the most recent code.

It should be fixed in a separate PR.

**Comment by reynoldtan** [comment]
Fix ready in bug-total-pages branch and in PR: https://github.com/UofS-Pulse-Binfo/tripal_ws_brapi/pull/32 Total page error

**Comment by laceysanderson** [comment]
Fixed
