### ISSUE TITLE
Configuration Menu Review

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/tripal_ws_brapi#2]
## No versions set on install
When I first install the module, none of the versions are set. This means any call I try comes back "Unsupported version number". Instead, the most recent 1.x and 2.x versions should be set by default.
<img width="1145" alt="Screen Shot 2020-04-08 at 4 23 49 PM" src="https://user-images.githubusercontent.com/1566301/78839290-680dd580-79b5-11ea-85ec-9ed89e26e0e1.png">

## Module config: Better help text
This page could use some better help text. Specifically,
- it's not clear what the vocabulary is used for.
- menu levels is not intuitive unless your a drupal developer. Perhaps URL prefix?
- the description for page result limit is incorrect.
- The Create block is confusing... I would leave the black create box out since the submit button is sufficient.

<img width="1433" alt="Screen Shot 2020-04-08 at 5 02 47 PM" src="https://user-images.githubusercontent.com/1566301/78841536-d86b2580-79ba-11ea-8904-5254728719c9.png">

## Version Config: Better help text

- It is not clear what the default is for... Maybe add a * in the header and example at the bottom.

<img width="1433" alt="Screen Shot 2020-04-08 at 5 05 32 PM" src="https://user-images.githubusercontent.com/1566301/78841688-4283ca80-79bb-11ea-8342-36ae8ba2f8eb.png">

## Calls Config: Must restrict?

When I try to configure a call without entering a way to restrict it, I receive validation error. However, I may want to show all records in the stock table without restricting. In this case, I do not need to configure this call? If so then the validation error should make that clear and/or there should be help text to that effect.

<img width="1433" alt="Screen Shot 2020-04-08 at 5 08 16 PM" src="https://user-images.githubusercontent.com/1566301/78841962-fbe2a000-79bb-11ea-961f-3c4f43b5dc66.png">

## Calls Config: Cannot support multiple type_ids?

The way configuration is currently developed I cannot say: germplasm includes any cultivar or accession which is what we need for KnowPulse.

**Comment by reynoldtan** [comment]
![Screen Shot 2020-04-17 at 10 19 23 AM (2)](https://user-images.githubusercontent.com/15472253/79591850-55229180-8096-11ea-8e71-6af69874c5f0.png)

Configuration items now come with a help text tooltip and now supports multiple criteria selection.

**To create multi-value criteria**
1. Select a call and term or value and click Add configuration in Configure: Calls tab.
2. List table will update showing the new configuration.
3. Re-select the same call in the form, other configuration elements will auto select except the term field (when restrict by typeid) or value field (when restrict by prop table) to ease setup.
4. Click add configuration button. List table will update list showing multiple filters selected under the same call.

I added an update to .install file to set a default version number (BrAPI 1.3) upon enable, please re-install module.

**Comment by laceysanderson** [comment]
Fixed
