### ISSUE TITLE
Unable to retrieve all trials within the same program

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/tripal_ws_brapi#20]
We should be able to retrieve all the `trials` (projects) with the same `program` (i.e. Lentil Breeding & Genetics). However, since the `programs` are indicated using `chado.projectprop` for a given `chado.project`, the `programId` is different for each `trial` even if the `program` is the same. This can be fixed by using `chado.project_relationship` to indicate `program` now that the `programs` are also stored in the `chado.project` table.

This bug was identified in PR #8 for the trials call. Since there are many outstanding PRs at this point, I haven't tested against the most recent code.

It should be fixed in a separate PR.

**Comment by reynoldtan** [comment]
Revised trail call to reflect method in the following PR
Issue #20 - Revised trials call
PR https://github.com/UofS-Pulse-Binfo/tripal_ws_brapi/pull/33

**Comment by laceysanderson** [comment]
Confirmed fixed 👍
