### ISSUE TITLE
All chado.projects shown in the trial call

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/tripal_ws_brapi#21]
Currently all records in the chado.project table appear to be listed for the trials call. For example, the `Breeding & Genetics` research program is shown even though that is not a trial. Ensure you restrict the same way it is for the content type.

This bug was identified in PR #8 for the trials call. Since there are many outstanding PRs at this point, I haven't tested against the most recent code.

It should be fixed in a separate PR.

**Comment by reynoldtan** [comment]
Revised trials call to exclude research areas from list of projects in PR https://github.com/UofS-Pulse-Binfo/tripal_ws_brapi/pull/33

**Comment by laceysanderson** [comment]
Fixed
