### ISSUE TITLE
missing info for people call is inconsistent

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/tripal_ws_brapi#22]
When checking the properties shown on contact pages, this does not seem to be a database inconsistency but may be at the application level. All should be changed to `""` as the long message is less program friendly and `n/a` is not correct, the email address is still applicable we just don't know it.

![Screen Shot 2020-08-05 at 1 12 02 PM](https://user-images.githubusercontent.com/1566301/89453905-24d23200-d71d-11ea-9e33-0124eea0ee61.png)

This bug was identified in PR #10 for the people call. Since there are many outstanding PRs at this point, I haven't tested against the most recent code.

It should be fixed in a separate PR.

**Comment by reynoldtan** [comment]
Revised call in this PR https://github.com/UofS-Pulse-Binfo/tripal_ws_brapi/pull/34.

**Comment by laceysanderson** [comment]
Fixed
