### ISSUE TITLE
All phenotype-focused calls should be retrieving data from chado.phenotype

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/tripal_ws_brapi#23]
All phenotype-focused calls should be retrieving data from chado.phenotype **NOT the UofS-Pulse-Binfo raw phenotypes tables!**

**Comment by reynoldtan** [comment]
All call previously using raw phenotypes tables have been revised to fetch data from phenotype and phenotypeprop table.

Below are calls with this issue:
1. Location PR https://github.com/UofS-Pulse-Binfo/tripal_ws_brapi/pull/11
2. Studies PR https://github.com/UofS-Pulse-Binfo/tripal_ws_brapi/pull/9
3. Trials PR https://github.com/UofS-Pulse-Binfo/tripal_ws_brapi/pull/24

**Comment by laceysanderson** [comment]
Addressed 👍
